export const RECEIVE_ITEMS_REQUEST = 'RECEIVE_ITEMS_REQUEST';
export const RECEIVE_ITEMS_SUCCESS = 'RECEIVE_ITEMS_SUCCESS';
export const RECEIVE_ITEMS_FAILURE = 'RECEIVE_ITEMS_FAILURE';

export const RECEIVE_ITEM_REQUEST = 'RECEIVE_ITEM_REQUEST';
export const RECEIVE_ITEM_SUCCESS = 'RECEIVE_ITEM_SUCCESS';
export const RECEIVE_ITEM_FAILURE = 'RECEIVE_ITEM_FAILURE';

export const EDIT_NAME = 'EDIT_NAME';
export const CANCEL_EDIT_NAME = 'CANCEL_EDIT_NAME';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const RESET_DETAIL_STATE = 'RESET_DETAIL_STATE';